### ISSUE TITLE
Android video crashes when switching from portrait to landscape

### ISSUE THREAD

**Issue by K232** [adamfisher/Xamarin.Forms.VideoPlayer#36]
Hi Adam,

using your video player in iOS works fine, and also in Android it plays well. But my Android application always crashes when I switch from Portrait to Landscape and vice versa. It does not matter whether I play the video or whether I pause it before switching. The app then automatically closes the video pages and returns to my main page. Then i could go to the video page and start the video again, and it will crash again when I switch from Portrait or Landscape to the other mode.

I load the video from stream, e.g. https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4 . I've tried to recreate the crash also in your Chill Player, but even changing the source to the stream does not reproduce the error, your Chill player still works fine switching back and forth between portrait and landscape....

I know it's difficult to support this problem as this only appears in my app and is not repeatable in yours, but maybe you nevertheless have any tips? Restricting the video to show in landscape only as written in #35 would probably also help to work around this problem.

Many thanks!

**Comment by K232** [comment]
This is the error message shown in Application Output:

```
[MediaPlayer] handleMessage msg:(3, 74, 0)
[MediaPlayer] handleMessage msg:(3, 74, 0)
[MediaPlayer] handleMessage msg:(3, 75, 0)
[MediaPlayer] handleMessage msg:(3, 75, 0)
[MediaPlayer] handleMessage msg:(3, 75, 0)
[MediaPlayer] handleMessage msg:(3, 75, 0)
[MediaPlayer] handleMessage msg:(3, 75, 0)
[MediaPlayer] handleMessage msg:(3, 75, 0)
[MediaPlayer] handleMessage msg:(3, 75, 0)
[MediaPlayer] handleMessage msg:(3, 75, 0)
[SurfaceView] updateWindow -- onWindowVisibilityChanged, visibility = 8, this = Octane.Xam.VideoPlayer.Android.Widget.VideoView{e9647e9 VFE...... ......ID 0,0-720,1120}
[SurfaceView] Changes: creating=false format=false size=false visible=true left=false top=false mUpdateWindowNeeded=false mReportDrawNeeded=false redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=false, this = Octane.Xam.VideoPlayer.Android.Widget.VideoView{e9647e9 VFE...... ......ID 0,0-720,1120}
[SurfaceView] Cur surface: Surface(name=null)/@0x2e8a3cc, this = Octane.Xam.VideoPlayer.Android.Widget.VideoView{e9647e9 VFE...... ......ID 0,0-720,1120}
[SurfaceView] New surface: Surface(name=null)/@0xabe1615, vis=false, frame=Rect(0, 160 - 720, 1280), this = Octane.Xam.VideoPlayer.Android.Widget.VideoView{e9647e9 VFE...... ......ID 0,0-720,1120}
[SurfaceView] Callback --> surfaceDestroyed, this = Octane.Xam.VideoPlayer.Android.Widget.VideoView{e9647e9 VFE...... ......ID 0,0-720,1120}
[SurfaceView] surfaceDestroyed callback +, this = Octane.Xam.VideoPlayer.Android.Widget.VideoView{e9647e9 VFE...... ......ID 0,0-720,1120}
[MediaHTTPConnection] teardownConnection
[System.out] Close in OkHttp
[NativeCrypto] ssl=0x9ba8ea80 NativeCrypto_SSL_interrupt
[NativeCrypto]  sslNotify, appData=0x9be45e00 ret=1
[NativeCrypto]  sslNotify, appData=0x9be45e00 ret=1
[System.out] close [socket][/192.168.2.3:35091]
[System.err] android.os.NetworkOnMainThreadException
[System.err] 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1288)
[System.err] 	at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1146)
[System.err] 	at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1141)
[System.err] 	at com.android.okhttp.Connection.closeIfOwnedBy(Connection.java:156)
[System.err] 	at com.android.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:75)
[System.err] 	at com.android.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:137)
[System.err] 	at com.android.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:135)
[System.err] 	at com.android.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:589)
[System.err] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:122)
[System.err] 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.disconnect(DelegatingHttpsURLConnection.java:93)
[System.err] 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.disconnect(HttpsURLConnectionImpl.java)
[System.err] 	at android.media.MediaHTTPConnection.teardownConnection(MediaHTTPConnection.java:147)
[System.err] 	at android.media.MediaHTTPConnection.disconnect(MediaHTTPConnection.java:136)
[System.err] 	at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:61)
[System.err] 	at android.os.Binder.execTransact(Binder.java:458)
[System.err] 	at android.media.MediaPlayer._reset(Native Method)
[System.err] 	at android.media.MediaPlayer.reset(MediaPlayer.java:1739)
[System.err] 	at android.widget.VideoView.release(VideoView.java:760)
[System.err] 	at android.widget.VideoView$7.surfaceDestroyed(VideoView.java:750)
[System.err] 	at android.view.SurfaceView.updateWindow(SurfaceView.java:710)
[System.err] 	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:282)
[System.err] 	at android.view.View.dispatchDetachedFromWindow(View.java:14740)
[System.err] 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
[System.err] 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
[System.err] 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
[System.err] 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
[System.err] 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
[System.err] 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
[System.err] 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
[System.err] 	at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4950)
[System.err] 	at android.view.ViewGroup.removeAllViews(ViewGroup.java:4896)
[System.err] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsAppCompatActivity.n_onDestroy(Native Method)
[System.err] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsAppCompatActivity.onDestroy(FormsAppCompatActivity.java:81)
[System.err] 	at android.app.Activity.performDestroy(Activity.java:6538)
[System.err] 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1149)
[System.err] 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4052)
[System.err] 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4083)
[System.err] 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4293)
[System.err] 	at android.app.ActivityThread.-wrap15(ActivityThread.java)
[System.err] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
[System.err] 	at android.os.Handler.dispatchMessage(Handler.java:111)
[System.err] 	at android.os.Looper.loop(Looper.java:207)
[System.err] 	at android.app.ActivityThread.main(ActivityThread.java:5728)
[System.err] 	at java.lang.reflect.Method.invoke(Native Method)
[System.err] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
[System.err] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
[System] FinalizerDaemon: finalize objects = 223
[OpenGLRenderer] ~CanvasContext() 0x9b4d9000
[SurfaceView] surfaceDestroyed callback -, this = Octane.Xam.VideoPlayer.Android.Widget.VideoView{e9647e9 VFE...... ......ID 0,0-720,1120}
[SurfaceView] Layout: x=0 y=160 w=720 h=1120, frame=Rect(0, 0 - 720, 1120), this = Octane.Xam.VideoPlayer.Android.Widget.VideoView{e9647e9 VFE...... ......ID 0,0-720,1120}
[SurfaceView] updateWindow -- onDetachedFromWindow, this = Octane.Xam.VideoPlayer.Android.Widget.VideoView{e9647e9 VFE...... ......ID 0,0-720,1120}
[InputMethodManager] START INPUT: md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer{ae77f0c VFE...... .F....ID 0,0-720,1280} ic=null tba=android.view.inputmethod.EditorInfo@34ea0bc controlFlags=#100
[Surface] Surface::disconnect(this=0x9ee86600,api=1)
[GraphicBuffer] unregister, handle(0xaf946990) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
[GraphicBuffer] unregister, handle(0xaf9473a0) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
[GraphicBuffer] unregister, handle(0xaf947480) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
[Surface] Surface::disconnect(this=0x9ee86600,api=1)
[WindowClient] Remove from mViews: com.android.internal.policy.PhoneWindow$DecorView{4fd563e V.E...... R.....ID 0,0-720,1280}, this = android.view.WindowManagerGlobal@2dd49a
[ztgl] asset != NULL
[ztgl] asset != NULL
[ztgl] asset != NULL
[ztgl] asset != NULL
[MultiWindowProxy] getServiceInstance failed!
[ztgl] asset != NULL
[ztgl] asset != NULL
[ztgl] asset != NULL
[ztgl] asset != NULL
[ztgl] asset != NULL
[ztgl] asset != NULL
[SettingsInterface]  from settings cache , name = android_id , value = 4e6e42187aa70e8b
[SettingsInterface]  from settings cache , name = android_id , value = 4e6e42187aa70e8b
[ztgl] asset != NULL
[ztgl] asset != NULL
[ztgl] asset != NULL
[ztgl] asset != NULL
[ztgl] asset != NULL
[art] Starting a blocking GC Explicit
[art] Explicit concurrent mark sweep GC freed 4905(337KB) AllocSpace objects, 1(68KB) LOS objects, 7% free, 47MB/51MB, paused 852us total 33.390ms
[OpenGLRenderer] ~CanvasContext() 0xaf964800
[PhoneWindow] DecorView setVisiblity: visibility = 4 ,Parent =null, this =com.android.internal.policy.PhoneWindow$DecorView{83f7aa7 I.E...... R.....ID 0,0-0,0}
[System.out] [CDS][DNS] getAllByNameImpl netId = 0
[WindowClient] Add to mViews: com.android.internal.policy.PhoneWindow$DecorView{83f7aa7 I.E...... R.....ID 0,0-0,0}, this = android.view.WindowManagerGlobal@2dd49a
```

**Comment by adamfisher** [comment]
From what I can tell, it looks like a `NetworkOnMainThreadException` SSL error experienced with the OKHttp library. It might have something to do with the way OKHttp is being used?

**Comment by K232** [comment]
I don't think so. I've used the same Url also in chill player and it works fine there. Additionally the crash appears whenever I switch mode so I don't think there is a relation to the network.... But I already thought it's hard to find :-( do you have any idea how to track or prevent this?

**Comment by K232** [comment]
I've found the following output in Android but these lines are also shown when running Chill Player so I guess they don't cause any problems?

VideoPlayer [INFO]: Video Source: https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
[MediaPlayer] Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

The clip plays fine nevertheless.

**Comment by K232** [comment]
Ah, I found the solution! I just forgot to add the ConfigurationChanges to the Activity in my MainActivity.cs. So if anyone else has the same problem, make sure to check this line in your MainActivity.cs:

[Activity(Label = "Chill Player", Icon = "@drawable/icon", MainLauncher = true, **ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation**)]

Now switch between portrait and landscape works fine! Great! :-)
